### ISSUE TITLE
Graphics Not Showing - Kubuntu 20.04

### ISSUE THREAD

**Issue by Max-Rodriguez** [keroserene/rickrollrc#34]
[Update]: HELP the script runs every time I open my terminal
[Fixed]: Why is it on .bashrc >:( Removed it 👍🏻 

The only thing that displays when executing the bit.ly command is "<3"

Here are my system specs:

** Operating System: Kubuntu 20.04 [ubuntu/debian]
** Desktop Environment - KDE Plasma Version 5.18.5
** Kernel Version - 5.4.0-64-generic
** OS Type - 64-bit

**Comment by cturland** [comment]
Same here. Running latest version of Ubuntu. It says there is a command error on line 98

**Comment by Max-Rodriguez** [comment]
Runs perfectly fine on Fedora 33 Workstation!
