### ISSUE TITLE
Original site offline 

### ISSUE THREAD

**Issue by CryptoDragonLady** [keroserene/rickrollrc#42]
I found the files in the internet archive. I hosted them in GitHub for posterity. I forked the repo and my changes are here
https://github.com/CryptoDragonLady/rickrollrc

**Comment by rrthomas** [comment]
Many thanks for this @CryptoDragonLady, I noticed just now that `suod` was broken, which obviously means my workflow is no longer interrupted, which was a problem.

**Comment by keroserene** [comment]
Thanks for ensuring the workflow interruptions remain uninterrupted!  I've restored the originals as well. (now with tls)
